# ── Backend ───────────────────────────────────────────────────────
backend        = "glx";
vsync          = true;
glx-no-stencil = true;
use-damage     = true;

# ── Esquinas redondeadas ──────────────────────────────────────────
corner-radius = 12;
rounded-corners-exclude = [
    "class_g = 'Polybar'",
    "class_g = 'Dunst'",
    "class_g = 'Bspwm'",
    "class_i = 'presel_feedback'",
    "class_g = 'slop'"
];

# ── Sombras ───────────────────────────────────────────────────────
shadow         = true;
shadow-radius  = 18;
shadow-offset-x = -14;
shadow-offset-y = -10;
shadow-opacity = 0.45;
shadow-exclude = [
    "name = 'Notification'",
    "class_g = 'Conky'",
    "class_g = 'Bspwm'",
    "class_i = 'presel_feedback'",
    "_GTK_FRAME_EXTENTS@"
];

# ── Blur (frosted glass) ──────────────────────────────────────────
blur-method = "dual_kawase";
blur-strength = 4;
blur-background = true;
blur-background-exclude = [
    "window_type = 'dock'",
    "class_g = 'slop'",
    "class_i = 'presel_feedback'"
];

# ── Opacidad ──────────────────────────────────────────────────────
inactive-opacity          = 1.0;
active-opacity            = 1.0;
frame-opacity             = 1.0;
inactive-opacity-override = false;

opacity-rule = [
    "10:class_g  = 'Bspwm'",
    "10:class_i  = 'presel_feedback'",
    "92:class_g  = 'kitty'       && !focused",
    "92:class_g  = 'st-256color' && !focused",
    "100:class_g = 'firefox'",
    "100:class_g = 'Steam'",
    "100:class_g = 'mpv'"
];

# ── Fade ──────────────────────────────────────────────────────────
fading        = true;
fade-in-step  = 0.06;
fade-out-step = 0.06;
fade-delta    = 5;

wintypes: {
    popup_menu    = { opacity = 0.95; };
    dropdown_menu = { opacity = 0.95; };
    dnd           = { shadow = false; };
    dock          = { shadow = false; blur-background = false; };
    tooltip       = { fade = true; shadow = true; opacity = 0.95; focus = true; };
};
